### ISSUE TITLE
Installer file name

### ISSUE THREAD

**Issue by Starcounter-Jack** [Polyjuice/Polyjuice#1]
Installer name should be

```
Polyjuice-DevelopNightlyBuilds-2.0.2918-Setup.exe
```

Right now it is not.

**Comment by warpech** [comment]
Currently, the file name is `Starcounter-Polyjuice-DevelopNightlyBuilds-2.0.3196-Setup.exe`. It should be `Polyjuice-DevelopNightlyBuilds-2.0.3196-Setup.exe`.

In other words, let's not introduce the installer as "Polyjuice edition of Starcounter". It is proudly "Polyjuice", of which Starcounter is just a humble core component.

Just as when you are installing Chrome, the installer is called `ChromeSetup.exe`, not `ChromiumChromeSetup.exe`.

**Comment by warpech** [comment]
Closing as outdated. We are not using the word Polyjuice at all right now
