### ISSUE TITLE
Routing to apps through "host" apps

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#11]
As discussed today with @Starcounter-Jack and @alemoi, we would like the URL scheme for standalone apps to be no different than apps accessed through "a launcher".

Consider a URL: `<a href="/people/person/5">Name</a>`. When clicked or accessed through a bookmark:
 - it should load in Launcher, if Launcher is running,
 - it shoud load in People standalone mode, if Launcher is stopped.

**Idea 1**: A launcher (or any app that wants to serve as a UI frame) registers itself as a default entry point (`Db.SetDefaultHost("/launcher/workspace")`) in `Main()`. 

As an extention to this idea, it would be possible to use host names as different entry points (see HTTP/1.1 `Host` header: http://superuser.com/questions/234292/how-is-a-subdomain-passed-to-the-webserver).

**Idea 2**: A launcher uses a wildcard handler to catch all the requests, e.g.:

```c#
Handle.GET("/{*}", (string appName) => {
  workspaces[appName] = X.GET("/" + appName, () => {
    return new Page();
  });
});
Handle.GET("/{*}/{*}", (string appName, string url) => {
  workspaces[appName] = X.GET("/" + appName + "/" + url, () => {
    return new Page();
  });
});
```

**Comment by alemoi** [comment]
I suppose, after introducing middleware filters, this issue seems to be irrelevant, so I am closing it. Please reopen if needed :)
