### ISSUE TITLE
Problems discovered in March demo praparation

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#13]
Please share your problems discovered while preparing for March demo here. We can then decide which problems get explained in patterns (#12) and which need to become a issue to be fixed.

**Comment by alemoi** [comment]
Is it only problems we should mention here or even minor difficulties/"things to improve" here as well?

**Comment by andwah** [comment]
1. If several apps expose a [Save] button (let's say on a "Person").  Both buttons may do different stuff on saving.  (the end-user will probably "hide" one of the buttons.). Then one apps "Save" button will never be called and maybe important code will never be executed.

2. How do we handle redirects,  If in one app's code the developer wants to go to another page (url).
Example. The user do not have permission to visit an url "/person/123" according to one app, but another app will allow this. It means that the first app will return "401 Unauthorized" and the other one will return a page json.

**Comment by warpech** [comment]
@alemoi: minor difficulties and things to improve are especially welcome!

**Comment by warpech** [comment]
1. moved to a separate issue https://github.com/Polyjuice/Polyjuice/issues/62

2. Any proposals how to wrap this as a general issue? Maybe the pattern that you described is actually OK?

**Comment by warpech** [comment]
2 . Moved to a separate issue https://github.com/Starcounter/RebelsLounge/issues/35 

Closing this issue
