### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#14]
Should we have a default icon pack distributed with Starcounter? I think so!

Choices we have:
- icon fonts:
 - [Font Awesome](http://fortawesome.github.io/Font-Awesome/) - 519 icons, MIT license
 - custom build of multiple MIT license icon fonts into a single font (https://icomoon.io/, http://fontello.com/)
 - icons8 - 2500 *beautiful* icons in 4 styles, commercial but affordable
- custom elements:
 - [core-icon](https://www.polymer-project.org/0.5/components/core-icon/demo.html) - 200 icons, BSD license, future uncertain

I vouch for icons8

**Comment by andwah** [comment]
I dont think we should include any icons, which ever we choose we will choose the wrong one :-(
App developers will probably want to use there own icon.

But if we are going to include a theme style with starcounter then i think we may also include icons, why not all of them :-)

**Comment by warpech** [comment]
Exactly, it is the same problem as with themes.

If we don't include icons, we will end up with apps including their own icons...

In result we will have:
- icon overlap, if apps load the same icons from different locations
- icon collisions, if apps load same font (e.g. FontAwesome) in different versions without renaming the font
- possibly chaotic visual style

The best would be if the app developers created a custom build of a icon font like FontAwesome with a custom font name and including only the icons that they use. But this is a unrealistic expectation and totally unpractical for development.

**Comment by warpech** [comment]
As pointed out by Konstantin in #29, Twitter Bootstrap comes with its own icon font "Glyphicons Halflings", with a commercial free-to-use kind of [license](http://glyphicons.com/license/):

> GLYPHICONS Halflings are also a part of Bootstrap from Twitter, and they are released under the same license as Bootstrap. While you are not required to include attribution on your Bootstrap-based projects, I would certainly appreciate a visible link back to GLYPHICONS.com in any place you find appropriate (footer, docs, etc).

If I am not wrong, Glyphicons Halflings has a similar API to Font Awesome, and they can be used side by side. I checked the list of icons and I don't find it very useful for a business app suite.

I think it can be used for the beginning. We can add Font Awesome to /sys/ if app developers request it.

I still believe that Icons8 have more distinguished designs and a choice of icons that is actually useful for business oriented apps.

**Comment by warpech** [comment]
Archiving
