### ISSUE TITLE
Close issue trackers in apps

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#16]
Small apps, such as Cartographer, do not need it's own issue tracker. This issue tracker (Polyjuice/Polyjuice) will be used to track problems with it.

**Comment by alemoi** [comment]
Just removed the issue tracker from Cartographer.

**Comment by tomalec** [comment]
What about [Polyjuice/Launcher](https://github.com/Polyjuice/Launcher) vs [Polyjuice/Polyjuice](https://github.com/Polyjuice/Polyjuice)?

**Comment by warpech** [comment]
We will keep these two. 

https://github.com/Polyjuice/Launcher is for problems regarding... Launcher :) But whenever there is a problem with Launcher + some other app, then https://github.com/Polyjuice/Polyjuice is the correct place to post about it

**Comment by warpech** [comment]
I think this issue was wrong. Maintaining a single issue board has other problems - mixing of issue concerns.

To search issues in different repos use GitHub Advanced Search:
 
- [Polyjuice open issues, from newest](https://github.com/search?l=&o=desc&q=user%3Apolyjuice+state%3Aopen&ref=advsearch&s=created&type=Issues&utf8=%E2%9C%93)
- [Juicy open issues, from newest](https://github.com/search?l=&o=desc&q=user%3Ajuicy+state%3Aopen&ref=advsearch&s=created&type=Issues&utf8=%E2%9C%93)
- [Starcounter open issues, from newest](https://github.com/search?l=&o=desc&q=user%3Astarcounter+state%3Aopen&ref=advsearch&s=created&type=Issues&utf8=%E2%9C%93)
- [PuppetJS open issues, from newest](https://github.com/search?l=&o=desc&q=user%3Apuppetjs+state%3Aopen&ref=advsearch&s=created&type=Issues&utf8=%E2%9C%93)
- [JSON-Patch open issues, from newest](https://github.com/search?l=&o=desc&q=user%3Astarcounter-jack+state%3Aopen&ref=advsearch&s=created&type=Issues&utf8=%E2%9C%93)
- [ALL open issues, from newest](https://github.com/search?o=desc&q=user%3Apolyjuice+user%3Ajuicy+user%3Astarcounter+user%3Apuppetjs+user%3Astarcounter-jack+state%3Aopen&ref=searchresults&s=created&type=Issues&utf8=%E2%9C%93)
