### ISSUE TITLE
Coding style and rules

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#17]
There are many developers working on Polyjuice apps using different tools.
This leads to different code style like:

1. Different tab size.
2. Different spacing: `if (a == b) {` - `if(a == b){` and so on.
3. Different quotes inside html: `<div class='div'></div>` - `<div class="div"></div>`.
4. Closed & not closed single html tags: `<input type="text">` - `<input type="text" />`.

A `.js` or `.html` file looks ugly when different developers write different pieces of code in different style.
Even worse happens when developers "fix" code of each other if it is written against current document format.

**Comment by warpech** [comment]
Duplicate of #12. Could you paste it there and close this one?

**Comment by warpech** [comment]
This is similar to #12 but actually different. #12 is about design practices (what is the project structure, etc) and this one is about coding style (tabulation, quotes, etc)

**Comment by tomalec** [comment]
For our custom elements, we have once talked about keeping same [editorconfig](http://editorconfig.org/) for every project.

**Comment by warpech** [comment]
I created a stub page: https://github.com/Polyjuice/Polyjuice/wiki/Coding-Style

+1 about editorconfig

I was not able to find a nice and short style guide for C# as a reference point. Some longish and outdated guides:

- http://www.aspdotnet-suresh.com/2010/04/c-coding-standards-and-best-programming.html
- http://se.inf.ethz.ch/old/teaching/ss2007/251-0290-00/project/CSharpCodingStandards.pdf

Other frameworks have nailed it:

- https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md
- https://github.com/airbnb/javascript

But some are way too specific:

- https://github.com/bbatsov/ruby-style-guide & https://github.com/bbatsov/rails-style-guide

**Comment by warpech** [comment]
@miyconst please expand the wiki stub with anything you find useful and assign it back to me for review when done

It would be really good for credibility if the rules in the style guide would be backed with a link to other styles that include that rule.

**Comment by miyconst** [comment]
@warpech, @tomalec here are two small wiki pages.

https://github.com/Polyjuice/Polyjuice/wiki/JavaScript-code-formatting
https://github.com/Polyjuice/Polyjuice/wiki/JavaScript-common-practices

Please, check them out and let me know what do you think.

**Comment by tomalec** [comment]
I think it would be nice to have a short HO and agree on each point you mentioned.

BTW, as usual Web Components people gives us something we need right in time https://twitter.com/addyosmani/status/582913556485677056/photo/1

**Comment by miyconst** [comment]
@tomalec, HO call would be great.

JSCS seems to be a powerful tool.

**Comment by miyconst** [comment]
editorconfig is not going to implement some important features like:
- curly_bracket_next_line
- spaces_around_operators
- spaces_around_brackets
- indent_brace_style

https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

**Comment by miyconst** [comment]
A page with some items about c#.
https://github.com/Polyjuice/Polyjuice/wiki/C%23-code-formatting

**Comment by miyconst** [comment]
Some time ago @warpech disagreed with `me` variable in JavaScript code. I agreed to use `that` instead of `me`.

Updated wiki page.

I guess, there is nothing more I can do without discussion with other developers.

**Comment by miyconst** [comment]
I came across a presentation about JavaScript code: https://www.youtube.com/watch?v=JVlfj7mQZPo

It's not that I really like it, but some of the points are very reasonable. The presentation mentions ESLint as a code checker, it has predefined set of rules: http://eslint.org/docs/rules/.

The list is quite big, but I like the idea of having some rules and following them by entire team.

cc @warpech, @tomalec

**Comment by tomalec** [comment]
I think we should prepare our own jscs -  http://jscs.info/  keep it in a repo, and use  it in our editors.

**Comment by miyconst** [comment]
+1 for jscs.info.

**Comment by miyconst** [comment]
We might consider using some for those new/crazy staff added to ECMAScript 6, as we are targeting for the most recent and future proof solutions.

**Comment by tomalec** [comment]
@warpech, @miyconst how about HO, in which we would go through rules list for jscs and setup one for us?

**Comment by miyconst** [comment]
Would be great.

**Comment by warpech** [comment]
We need to have something that applies to all of us. The most of JS code is in PuppetJS. There is plenty of JS in Web Components. Can ESLint and JSCS check HTML files for JavaScript?

Since @tomalec wrote the most of JS that we have, I propose that he creates the settings for JSCS and sends them for @miyconst and me for acceptance. Can the settings for ESLint be saved in a single file as well?

Please note that such settings are only a development help for us and should not be imposed on devs using our platform.

**Comment by miyconst** [comment]
Closing this issue as too old.
