### ISSUE TITLE
Create a GoogleSignIn app

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#18]
A new app should be created to demonstrate that we can have apps doing the same thing differently.

Create a new project Polyjuice/GoogleSignIn. 

Take inspiration from https://github.com/Polyjuice/SignInApp how to sign in and take this Custom Element to integrate with Google API if possible https://github.com/GoogleWebComponents/google-signin

SignIn and GoogleSignIn can be run together or just one.

**Comment by warpech** [comment]
If `<google-signin>` doesn't work, let's use https://developers.google.com/+/web/signin/ then (because the custom element is a thin wrapper around that API)

**Comment by miyconst** [comment]
Here is the first version of GoogleSignIn application.
https://github.com/Polyjuice/GoogleSignIn

Things to do:
- [ ] Register a real Google Application and obtain its ClientID.
- [ ] RedirectUrl does not work yet.
- [ ] Nice icon.
- [ ] Make it work together with SignInApp.
- [ ] Fix UserAdminApp and test with GoogleSignIn.

**Comment by warpech** [comment]
@miyconst could you create tickets for the above issues (if still applicable) in https://github.com/Polyjuice/GoogleSignIn and close this issue? Thanks!

**Comment by miyconst** [comment]
Done.
