### ISSUE TITLE
Upload does not work in Images app

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#19]
Upload does not work in Images app.

Brief investigation shows that the POST handler is not called for image upload in the Images app.

May be a problem with recent changes in removing `/launcher/workspace` from URLs.

@alemoi could you take a look?

**Comment by alemoi** [comment]
Sure, I will take a look!

**Comment by warpech** [comment]
Any ideas about this?

**Comment by miyconst** [comment]
I have tested Images app under the latest nighty build which is:
`Polyjuice-DevelopNightlyBuilds-2.0.3111 (Apr 3, 2015 2:59:48 AM)` and the POST handler is called as expected, probably @alemoi fixed it.

But there is another issue with headers.
Images app sets a header.
https://github.com/Polyjuice/Images/blob/master/ImageUpload.cs#L80
```csharp
response["x-file"] = System.Text.Encoding.Default.GetString(xfile.ToJsonUtf8());
```

And the header is not being send to the client.
I think, this is somehow related to the latest server side changes with cookies.

**Comment by alemoi** [comment]
I added new interface to add outgoing HTTP headers, same as for cookies: `Handle.AddOutgoingHeader`. Done via: 05883ebe9c05f2763837537d423cc1c6c6ff6617

**Comment by alemoi** [comment]
Modified Images app accordingly via: 55b476c65bc38a33dfa9bd24ba822ec0aeed7a72

**Comment by miyconst** [comment]
@alemoi, @warpech, file uploading works as expected.
I close the issue.
