### ISSUE TITLE
Installer texts

### ISSUE THREAD

**Issue by Starcounter-Jack** [Polyjuice/Polyjuice#2]
## Title

The title bar of the installer says ```Starcounter Setup```. It should read ```Polyjuice Setup```.

## Welcome Screen

The installer texts needs to be changed:

```
Welcome

That you for downloading Polyjuice!

Polyjuice is a application server that allows many apps to share data in real time. It allows you to create small and focused best-of-breed business apps that, together, beats the big and monolithic dinosaurs of yesteryear. 

This installer will also install Starcounter. Starcounter offers extreme.....[THIS SECTION FROM OLD INSTALLER]

Click install to accept........ and install Polyjuice.
```

## Next screen - Installation

Replace path Starcounter with Polyjuice.

## Next screen - Database Engine

Change ```Database Engine``` to ```Polyjuice Server```. This is also true for the left pane of the installer (where the different steps are listed).

## Next screen - Developer Tools

Replace ```Starcounter``` with ```Polyjuice```.

**Comment by warpech** [comment]
This is still valid

**Comment by dan31** [comment]
So, what is defined now (and will be printed, signed and hang on the wall):
* Starcounter is in-memory app engine (we originally had "in-memory application platform, that has been adjusted to "in-memory app engine", which is shorter and more concise);
* Polyjuice is the cloud and the marketplace.

So, guys, Polyjuice is not an application server! We decided to have one installer, and that installer must be Starcounter (see Marcin's #2782). But the question then: when you install Starcounter, should it offer you a connection to Polyjuice.com cloud?

**Comment by warpech** [comment]
Closing as outdated. We are not using the word Polyjuice at all right now
