### ISSUE TITLE
User should be able to get the level of the X.GET call hierarchy

### ISSUE THREAD

**Issue by alemoi** [Polyjuice/Polyjuice#22]
This should be suitable for determining what partial size to respond with. Initially for the external request the level value is 0, however the client should be able to overwrite this initial value by setting the HTTP header `X-Accept-Size` to some integer, then the counting starts from this value and increases on each internal X.GET call.

**Comment by alemoi** [comment]
Current level in handlers call hierarchy can now be accessed by reading static property `Handle.CallLevel`. This value is independent from edition and just provides the level of handler call. User can manually combine this value with, for example, HTTP header `X-Accept-Size` that provides an initial partial size and other custom solutions like this, but its outside the purpose of `Handle.CallLevel`. Done via commit: ed627846767e9332a265e7e39a07c3e685ef5bb7

**Comment by miyconst** [comment]
`Handle.CallLevel` works for me.

**Comment by alemoi** [comment]
Thank you for the response!
