### ISSUE TITLE
Make every app able to run standalone

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#25]
- [x] AppStore
- [x] AppStoreClient - by @miyconst
- [x] Barcodes - by @miyconst
- [ ] Cartographer
- [ ] GoogleSignIn
- [x] Images
- [x] Launcher
- [x] People - done, need some refactoring
- [x] Procurement - by @miyconst
- [x] Products - by @warpech 
- [ ] SignIn
- [x] Skyper
- [ ] User Admin

**Comment by tomalec** [comment]
@warpech, @miyconst Please note that now all apps should use [`<polyjuice-include>`](https://github.com/Polyjuice/polyjuice-include). So in standalone mode it will fallback to `imported-template`, while in Launcher it will get enhanced with layout management.

**Comment by warpech** [comment]
@miyconst could you migrate the apps to use `<polyjuice-include>`?

**Comment by miyconst** [comment]
Sure.

**Comment by miyconst** [comment]
https://github.com/Polyjuice/Procurement/commit/420201fd8b3fab7baa5bd0d59f48c9876802ad1b

**Comment by miyconst** [comment]
Barcodes, Images, People, Procurement, Products, Skyper, `launcher-root-partial` replaced with `polyjuice-include`.

**Comment by tomalec** [comment]
Sorry guys, but I have changed `<polyjuice-include>` so it does no longer work without `partial` attribute.

So all `<polyjuice-include>`s need to be changed, to `<polyjuice-include partial="{{}}">` or `<polyjuice-include partial="{{Page}}">`

It's not only to make code more declarative and explicit, but also to avoid infinite loop, for `<polyjuice-include>` that includes `<polyjuice-include>`, plus it makes it possible to attach `include.partial={}` in VanillaJs

**Comment by miyconst** [comment]
Barcodes, Images, Procurement, Products, Skyper, Chatter these apps have been updated.

**Comment by warpech** [comment]
All of the above apps are either updated or discontinued. Closing
