### ISSUE TITLE
Move Polyjuice/Wiki images to Polyjuice/Polyjuice wiki

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#27]
This repo is not needed: https://github.com/Polyjuice/Wiki
As any GitHub wiki is a git repo actually: https://github.com/Polyjuice/Polyjuice.wiki.git

More info: https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

**Comment by miyconst** [comment]
Done.
