### ISSUE TITLE
Sample REST authentication in SignIn

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#28]
SignIn app should support ability to authenticate using REST interface.

The design goal for a REST interface is to use the same handlers for JSON and HTML.

Include tests in SignIn (Node + Mocha, similarly to tests in https://github.com/Polyjuice/Launcher) that checks:
1) signing in
2) retrieving information about currently signed in user
3) retrieving information from another app that expects signed in user (this can be later moved to acceptance tests)
3) signing out

**Comment by miyconst** [comment]
@warpech I have checked how SignIn app works with `application/json`, `text/plain` accept header.

It works, but not as I would expect common api work.
The server returns entire model in json format, I would expect something like:

```javascript
{
    IsSignedIn: true,
    User: {
        Username: "admin"
    }
}
```

Third part applications have no idea of what labels, buttons, templates we have on the page.
Even more, they don't want to know about that.

**Comment by miyconst** [comment]
@warpech here is the end result:
https://github.com/Polyjuice/SignIn/blob/cookie-rework/test/test.js

The test requires UserAdminApp running and a specific user inside database.
This concerns me.
