### ISSUE TITLE
Add Bootstrap to installation /sys/ packages

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#29]
To achieve consistent look in applications, we decided to add Twitter Bootstrap (3.3.4) with Bootswatch Paper (3.3.4+1) theme to installation packages.

Me and @tomalec decided that it is a good idea to create our repo for the copy of Twitter Bootstrap with the applied theme. Otherwise it would be impossible to do automatic `rm -rf && bower install` in the StaticFiles directory.

Now the question is, should we:

1. include the theme as a separate file `/sys/bootstrap/dist/css/bootstrap-bootswatch-paper.css` (allowing access to the original Bootstrap) 
2. or replace the original `bootstrap.css` with the theme (as instructed in Bootswatch Paper installation instructions)

Since we create our repo anyway, I propose to go with the answer 2.

@tomalec, @andwah, @miyconst - WDYT?

**Comment by miyconst** [comment]
I like the 2-d option. New developers might be confused why `bootstrap.css` file works in different way compare to the original file.

Also I don't like to mess inside code of other vendors.

**Comment by andwah** [comment]
I also like option 1.  Then people can still use twitter bootstrap with another theme if they like.

**Comment by tomalec** [comment]
I would go for 2. as this is how Bootswatch says, so we would avoid bugs related to using it in a way it was not prepared for.

It will be our `polyjuice/bootstrap.css` not `twitter/bootstrap.css`, so I believe it's clear enough that is our custom theme. If people would like to use twitter bootstrap, the would probably use `twitter/bootstrap.css` anyways, to make sure the get what they want.

**Comment by warpech** [comment]
I am afraid that if we go for 1., we may end up with someone actually using `bootstrap.css` instead of `bootstrap-bootswatch-paper.css` - which give unpredictable result. If someone really wants to use another bootstrap theme than Bootswatch Paper (including the original theme), they can import it locally in their project.

**Comment by warpech** [comment]
As it turned out, the Bootswatch themes are also on GitHub: https://github.com/thomaspark/bootswatch

Since we use it unmodified, I decided to include Bootswatch themes via bower. The GitHub repo includes all the themes, of which we need only one. Hence, I disabled other themes in https://github.com/Starcounter/Starcounter/blob/develop/src/BuildSystem/Polyjuice/.gitignore

Bootswatch Paper theme can now be used as `<link rel="stylesheet" href="/sys/bootswatch/paper/bootstrap.css" />`. It will be available starting from next Starcounter nightly build.

@miyconst can you update People app then?

**Comment by miyconst** [comment]
@warpech sure, will do that tomorrow.

**Comment by miyconst** [comment]
@warpech should I also use icons from the bootstrap package?

**Comment by warpech** [comment]
I responded generally in #14, but in short words - we can use it but only where it makes sense. I think that a good design can go far without icons ([Windows Phone](http://blogs.msdn.com/b/africaapps/archive/2014/03/08/ux-guidelines-for-windows-phone-8.aspx) is a good example)

**Comment by warpech** [comment]
Bootswatch Paper theme is now distributed with Starcounter: 

- code: https://github.com/Starcounter/Starcounter/tree/develop/src/BuildSystem/Polyjuice/StaticFiles/sys/bootswatch
- loader: https://github.com/Starcounter/Starcounter/blob/develop/src/BuildSystem/Polyjuice/StaticFiles/sys/bootstrap.html

It can be abstractly imported by using this line in a partial:

```html
<link rel="import" href="/sys/bootstrap.html">
```
