### ISSUE TITLE
Migrate all of the project to the new project structure

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#31]
https://github.com/Polyjuice/Polyjuice/wiki/Polyjuice-project-structure

**Comment by miyconst** [comment]
The apps to rework:

- [ ] Launcher, https://github.com/Polyjuice/Launcher
- [ ] UserAdminApp, https://github.com/Polyjuice/UserAdminApp
- [ ] Procurement, https://github.com/Polyjuice/Procurement
- [ ] Skyper, https://github.com/Polyjuice/Skyper
- [ ] Products, https://github.com/Polyjuice/Products
- [ ] Cartographer, https://github.com/Polyjuice/Cartographer
- [ ] Barcodes, https://github.com/Polyjuice/Barcodes

**Comment by miyconst** [comment]
UserAdmin app has some sub-folders inside `viewmodels` folders. We have not yet decided correct structure for sub-folders and sub-namespaces, so I left it as is.

**Comment by warpech** [comment]
As discussed on Skype, the subfolders should not be mirrored in namespace. The namespace for the demo apps should be flat (just the project name).

For the viewmodels that have a HTML file but use Page class directly in C# (without extending it), the filename should contain the `Page` word. Hence, in People app rename the file `AppIcon.html` to `AppIconPage.html`

**Comment by miyconst** [comment]
UserAdmin app finished.

**Comment by miyconst** [comment]
Skyper: https://github.com/Polyjuice/Skyper/commit/8dbf99c972ee5db78525920d095888175920316a, https://github.com/Polyjuice/Skyper/commit/218e8b3be9a8fce363e6dc6fe0b0eb91514ea4af

**Comment by miyconst** [comment]
@warpech is there any app to rework or I should close the issue?

**Comment by warpech** [comment]
Nope, done! :trophy:
