### ISSUE TITLE
$ and Namespace inside Json viewmodel

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#33]
What for this line of code?
```json
"$": { "Namespace": "UserAdmin.Partials.Administrator" }
```

Should I use it? If so then when? I never passed namespace in my ViewPage.json, but saw this in older applications.

**Comment by warpech** [comment]
@chrhol, could you explain or (better) give a link to a wiki page that explains it?

**Comment by chrhol** [comment]
Thanks for the bump @warpech. I saw this issue but I forgot to answer it.

This is part of https://github.com/Starcounter/Starcounter/issues/2650 (and https://github.com/Starcounter/Starcounter/issues/2649).

You use it when you want the generated TypedJson object to be inside a specific namespace and there is no codebind-file.
Having a single "$" just means it's metadata for the root-object (metadata for a property is $ + name).

Lets take some time with @Starcounter-Jack next week and see if we can find some better way to define these things or if we can get rid of it from the json altogether.

**Comment by miyconst** [comment]
So, `$` should be used only if `*.json` file does not have codebind file and should be in a specific namespace, correct?

**Comment by chrhol** [comment]
In this case, yes. 

There are a few other possible paramters as well that can be specified that needs to be documented (preferable after we review it).
