### ISSUE TITLE
Layout styles depends on application start number, but should not

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#34]
Layout style key is generated as `[MainAppName, InjectedAppName1, InjectedAppName2].join("&")`. If app 1 was started before app 2 then the key will look like `MainApp&App1&App2`, but if app 2 was started before app 1 then key will look like `MainApp&App2&App1`. 

This leads to different layout key for same page with same applications. The key should be the same regardless application start position. 

The exception was found with these three apps:
- Products
- Procurement
- Barcodes

**Comment by tomalec** [comment]
There is already work in progres (https://github.com/Polyjuice/Launcher/tree/persistent_tiles_setup).

We have described final solution at wiki: https://github.com/Polyjuice/Launcher/wiki/Layout-setup
Currently, we need _Partial Id_ as described at https://github.com/Polyjuice/Launcher/wiki/Merged-JSON-Response and just use it as a key for juicy tiles setup.
