### ISSUE TITLE
Could we remove juicytilessetup 404 error?

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#35]
This error is really annoying when looking for a particular error on console.

Could there be a handler which would catch all of those requests and response that there is no style for this element, but with code 200 instead of 404.

**Comment by tomalec** [comment]
Once we will implement Partials and Layouts as in wiki it should not happen (at least in regular case).
https://github.com/Polyjuice/Launcher/wiki/Layout-setup#layout-fetching-algorithm

**Comment by warpech** [comment]
I didn't see this error recently. Can this be closed?

**Comment by miyconst** [comment]
Yes.
