### ISSUE TITLE
Add generatestyles handler

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#36]
Add generatestyles handler to 
https://github.com/Polyjuice/Polyjuice/blob/master/src/JuicyTilesSetupHandlers.cs

Instead of Laucnher.

**Comment by tomalec** [comment]
What do you mean by generatestyles handler?

I would rather say that we should move entire JuicyTileSetup fetching to the Launcher.
And those handlers does not generate styles, it is only key-value store.

**Comment by miyconst** [comment]
@tomalec this is an issue for me.

I have created a handler in launcher, which generates .sql script for layout styles.
It should be moved to Polyjuice project, to don't forget I created this issue.

**Comment by miyconst** [comment]
Done.

Now there is a handler to generate sql statement for layout styles per app:

`http://localhost:8080/launcher/generatestyles/AppName`

For example:
`http://localhost:8080/launcher/generatestyles/products` will generate sql for styles of Products application.
