### ISSUE TITLE
Layout editor: add possibility to delete elements from tree

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#37]

**Comment by tomalec** [comment]
By delete, do you mean delete setup item entry for an element and fall back to default one?

**Comment by miyconst** [comment]
Yes, I meant delete entire branch of styles and revert it back to default. This would be very useful when an element removed from a page, but styles for the element still persist.

**Comment by warpech** [comment]
I can feel the need, but I wonder about few things:

1. Wouldn't "Reset styles" be a better name?
2. What UI do you propose? Context menu on a tree element?
3. What about groups? Resetting a group would actually *ungroup* it and move children into original places.
4. So maybe we need 3 buttons then: "Reset styles", "Reset styles including children", "Ungroup"

**Comment by tomalec** [comment]
:+1: form hall. Wat about "recursively" instead of "including children"?

**Comment by miyconst** [comment]
1. Yes, Reset styles would be a better name.
2. I thought it will be another top panel button, probably next to Unhide.
3. We already have Ungroup button. Reset styles should remove all groups and any styles for the selected elements, and if it was a group, then the elements inside it will be moved to the root container.
4. As I said, we already have Ungroup button, and I don't really see the need of "Reset styles" button, the only one would be useful for me is "Reset styles recursively".

**Comment by warpech** [comment]
Re: 3. If resetting a group ungroups it, what about the priority of elements that were in the group? Will they inherit the deleted group's priority, or retain their original priority? I think inheriting the group's priority makes sense. 

But I feel that actually it makes more sense that the group should survive the reset (but not the subgroups). If I wan't to reset and ungroup, I will hit "Reset" and then "Ungroup".

**Comment by Starcounter-Jack** [comment]
The priority of the group majes sense

**Comment by miyconst** [comment]
This is interesting, I agree with @warpech, resetting a group should reset styles for elements inside and ungroup all groups inside, but the original group should stay unchanged.

**Comment by warpech** [comment]
So, agreed that:
- "Reset styles" button on a group should:
  - reset the layout setup of the subject group (except priority)
  - reset the layout setup of the elements inside the subject group (including priority)
  - ungroup all groups inside (but not the subject group)
- "Ungroup" button should:
  - copy the priority of the subject group onto the elements inside the group
  - ungroup the subject group (but not the groups inside)

Now for the basic question, regarding the following:

> delete entire branch of styles and revert it back to default.

What in case there was default styles provided with the app? Should it revert to these styles or remove layout style completely? I think it should revert to the default styles provided with the app.

**Comment by miyconst** [comment]
But how do we know what styles are *default* for an app? This is not yet implemented, I guess.

**Comment by warpech** [comment]
That can get implemented after point 1a of https://github.com/Polyjuice/Polyjuice/issues/42.

If you think that the "Reset styles" button should remove all styles without restoring the default, then it can be done now.

**Comment by miyconst** [comment]
Actually, I came up with this issue when I was editing default styles of an app.

Before the last demo I had to remove an element from a page, and this broke layout, so my goal was to reset layout of that piece of html, after the reset there would not be any styles at all.

And if the reset button resets styles to its default value, then the main purpose of the issue is not accomplished.

**Comment by tomalec** [comment]
Just to note, we do not require 1a. from #42 to achieve default layouts per app, we just require a place on server-side to merge juicy tiles setups for all apps.

**Comment by warpech** [comment]
Agreed. Please make the "Reset styles" button (and changes to "Ungroup" button) according to the description in https://github.com/Polyjuice/Polyjuice/issues/37#issuecomment-100802905, which was updated to say that "Reset styles" means *remove all the layout information, even the default layout that came from the app*.

**Comment by miyconst** [comment]
Just now tried to implement the feature, and it looks like there is no way to do it.
After short discussion with @tomalec we agreed that:

1. If a developer removes an element from a page, then he has to manually edit default styles and remove related tile-setup.
2. The *reset styles* button should ungroup all of the groups inside and revert item values to default value, but not remove styles of no longer existing elements.

This small example helps to understand what is going on:

1. Two groups in an application: group A contains tiles (1, 2, 3) and group B contains (4, 5, 6);
2. Some styles applied to the setup.
3. Element 3 removed by developer.
4. In the Layout editor we will get: group A with (1, 2, 3 (previous 4)) and group B with (4, 5, *), previous (5, 6). The * is a white gap for the removed element.

Resetting styles won't move elements 3,4,5 to the group B and leave only 1,2 in group A, because there is no way to distinguish sibling elements in a container. They all get id by its sort number, like `Images/1`, `Images/2`, `Images/3`.

This is only possible when each tile has its own unique id, it might be composed like `AppName/TileClass`, but this require unique class to each root element of an app, which is not good.

@warpech should I still make the reset styles button?

**Comment by warpech** [comment]
I think the above problem is a separate issue. "Reset styles" would still be functional, but works on the tiles currently in the group, not originally in the group.

To reset all styles in a template, disregarding (and actually ungrouping) the virtual groups, I need to hit "Reset styles" on `juicy-tile-list`, don't I?

**Comment by miyconst** [comment]
Okay, I do the Reset styles button.

Clear button removes styles for entire branch, not only selected group.
