### ISSUE TITLE
Layout editor: add possibility to set custom group name in tree

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#38]

**Comment by tomalec** [comment]
[`<juicy-tile-list>`](https://github.com/Juicy/juicy-tile-list)  supports it from long time ago, so it should go quite easy, and require only adding edit field.

**Comment by miyconst** [comment]
@tomalec I have added UI to edit group/element id, but it does not work.

The value being restored on page reload.

**Comment by miyconst** [comment]
@tomalec could you please also commit to Launcher?

`juicy-layout-editor` changes I have already committed with some of mine changes.
