### ISSUE TITLE
Layout editor: set width to 100% instead of screen width for new groups

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#39]
Width of new groups automatically set to its current width, which is wrong. When applying styles on a big monitor, then scroll appears when trying to view the page on a small monitor or with lower resolution.

The width for new groups should be automatically set to `100%`. Same should be applied for root groups.

**Comment by tomalec** [comment]
Some time ago we Agreed with Jocke and Marcin that we should create a group as small as possible, so there is an algorithm that finds the smallest dimensions.

Both solutions have pros and cons :/

@warpech do you have any comment?

**Comment by warpech** [comment]
I think 100% is the way to go for the group.

In long term, I think we should be fine using mostly relative values (`25%`, `50%`, `100%`, etc) for group and element widths and pixel values (`320px`, `960px`, 1280px`, etc) for responsive design breakpoints of a specific container width (once we have breakpoints).

Does it make sense to you?

**Comment by tomalec** [comment]
To sum up what I get from todays meeting, until juicy-tile-list features (fractions, tight groups, etc.) will be provided, we will use two buttons in editor:
 - New group / new smallest possible group - current "new group" functionality, that calculates smallest possible group containing selected element (now in `px` maybe in future we will keep it with `fr` or `px`)
 - New row / new group - creates new container `100%` x `auto` and put tiles there

**Comment by miyconst** [comment]
@tomalec, what is the difference between `New group` and `New row`? There is only one button on the control panel.

**Comment by tomalec** [comment]
The idea is to add a new button that would create `new row` - new group with `width: "100%"`.
`New smallest possible group` - will do what `new group` does currently.

**Comment by miyconst** [comment]
Okay, I may try to do that.
