### ISSUE TITLE
Installer Program Name

### ISSUE THREAD

**Issue by Starcounter-Jack** [Polyjuice/Polyjuice#4]
The program name in the installer is

`Starcounter Components`

Change to

`Polyjuice and Starcounter Components`

**Comment by andwah** [comment]
Where does this text exist?, i can not find it.

a screenshot would be nice

**Comment by dan31** [comment]
@andwah, naming has been reconsidered multiple times since Dec 2014 (I won't detail in that issue). Let's recap on recent Polyjuice meeting, please bump it (I see 4 issues regarding the installer). We will also have to adjust installer, which says that Starcounter is a database.

**Comment by warpech** [comment]
I tested both the current version and the version from Dec 10, 2014. In both cases this text is displayed in the UAC dialog:

![installer-1](https://cloud.githubusercontent.com/assets/566463/8230453/9fe54334-15c0-11e5-9b56-42395c37e1d9.png)

I couldn't find this text in any context other than the UAC dialog.

**Comment by warpech** [comment]
@dan31 I converted your comment into a separate issue: https://github.com/Starcounter/Starcounter/issues/2782. Please comment there if you wish

**Comment by warpech** [comment]
I just checked. Exactly the same text ("Starcounter Components") still appears in Windows UAC dialog before installation in Windows 10.

**Comment by warpech** [comment]
Closing as not that relevant
