### ISSUE TITLE
Stop launcher from tampering with certain requests to enable REST API

### ISSUE THREAD

**Issue by mtornwall** [Polyjuice/Polyjuice#41]
The way the launcher behaves right now (or rather, the way LauncherHelper behaves) makes it difficult to implement a REST API while the launcher is running. Since it installs a middleware filter to wrap the pages it serves in the launcher the responses from the REST API get garbled.

My current (incredibly ugly) work-around involves wrapping the middleware filter installed by LauncherHelper in another filter that first checks to see if the URL matches my REST API prefix, and if so aborts processing. If not, it proceeds with the launcher's middleware filter as usual:

    var oldHandler = Handle.middlewareFilters_[0].FilterRequest;
    Handle.middlewareFilters_[0].FilterRequest = (r) =>
    {
         if (r.Uri.StartsWith("/myapp/rest/resources", StringComparison.InvariantCultureIgnoreCase))
            return null;
        return oldHandler(r);
    };

Clearly this solution is not ideal. I would like to be able to register URL patterns or prefixes to be excluded from launcher wrapping.

**Comment by alemoi** [comment]
Thanks for the question! The idea was that when Launcher is running - it wraps ALL the existing responses from all handlers, since Launcher has a notion of "wrapper".

Just for me to understand, is there a reason to run Launcher and at the same time not expect it to wrap everything?

If it helps, you can simply turn off/on middleware filters "on the fly" without restarting the codehost as described here: https://github.com/Starcounter/Starcounter/issues/2680

**Comment by alemoi** [comment]
Probably you want a handler result that should never be wrapped?

**Comment by mtornwall** [comment]
> Probably you want a handler result that should never be wrapped?

Yes, exactly.

> Just for me to understand, is there a reason to run Launcher and at the same time not expect it to wrap everything?

The reason is that parts of my app are meant for humans to interact with through the browser (and in that scenario I want the launcher). However, I also have a part that needs to interact with another (external) application using REST calls.

**Comment by alemoi** [comment]
I was thinking about it and came up with a flag that can be set when registering a handler using `HandlerOptions`. The flag is used simply to skip the middleware filters.

**Comment by mtornwall** [comment]
Actually looking for a handler option like that was my first instinct, so to me it sounds like a good solution. :)

**Comment by alemoi** [comment]
Should be available via 947aea0c449b90121bed38bded7958cc9364a171
Please let us know!

**Comment by mtornwall** [comment]
This resolved the issue. Thanks!
