### ISSUE TITLE
Build a Fiddler App

### ISSUE THREAD

**Issue by andwah** [Polyjuice/Polyjuice#43]
![fiddler](https://cloud.githubusercontent.com/assets/2656996/7322218/f5dac6d2-eaa6-11e4-98e3-8b8ce96db3ef.png)

**Comment by warpech** [comment]
I searched for "fiddle" instead of "fiddler" and could not find this issue, hence I created a duplicate unintentionally: https://github.com/Starcounter/CompanyTrack/issues/67

**Comment by warpech** [comment]
Closing in favor of https://github.com/Starcounter/CompanyTrack/issues/67
