### ISSUE TITLE
Layout editor: replace default icon for an element

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#44]
Currently default icon for a simple element is a dash `-`, it should be replaced with some nice icon, maybe small rectangle or something like this.

**Comment by warpech** [comment]
I vote for having no icon for a simple element...

Alternatively, let's add some meaning to it:
- if this element has only div, span and text nodes, let's put a `Ｔ` icon
- otherwise let's put a `〈〉` icon

Reference screenshot how others do it:
![screenshot 2015-04-28 14 07 17](https://cloud.githubusercontent.com/assets/566463/7369187/f0bd8c1e-edaf-11e4-8cae-3b116780c7ac.png)

**Comment by miyconst** [comment]
The `T` and `<>` icons might look good, but this might need way too many calculations to determine type of a node.

**Comment by warpech** [comment]
I think this is acually a one liner in JS: 

```js
document.body.querySelector(":not(span):not(div)")
```

Replace `document.body` with the element and there you go! If we see it too much in Chrome Dev Tools Profiler, we can always remove it.

**Comment by miyconst** [comment]
You forgot about `em`, `b`, `strong`, `i` and other text tags. Not sure it is okay to run that long query selector for each tile.

**Comment by warpech** [comment]
Yeah, it slows down with multiple checks, but still few million checks per second: http://jsperf.com/queryselectorfun

And we usually have no more than thousand elements in the tree, don't we?

**Comment by miyconst** [comment]
Seems to be fast enough. Then what way to go? Remove `-` icon or replace it with `T` and `<>`?

**Comment by warpech** [comment]
Yes, let's try that!

**Comment by miyconst** [comment]
Removed icon for simple elements, looks good for me.

**Comment by warpech** [comment]
It seems I had trouble to read with understanding yesterday. I answered "Yes" to a "X or Y" question, but I guess you could assumed that I advocate for `T` and `<>` buttons since the beginning, so what went wrong with that?

**Comment by miyconst** [comment]
Sidebar tree uses Polymer/core-icon, and there is no nice icon for `T` and `<>`. I tried to use the closest one, but it looks ugly.

I could try using bootstrap icons, but there is also no such icons, the closest are: `glyphicon glyphicon-text-size`, `glyphicon glyphicon-text-width`, `glyphicon glyphicon-retweet`.

http://getbootstrap.com/components/#glyphicons

Anyway, bootstrap is not even included in juicy-tile-editor.

Should I just include some custom icon images?

**Comment by warpech** [comment]
Ah, I understand. 

Maybe let's use SVG for icons? Then we are free to easily replace icons when desired.

This is not urgent.

**Comment by warpech** [comment]
Another web app that has a nice tree: https://create.goocreate.com/

![screenshot 2015-04-30 10 48 15](https://cloud.githubusercontent.com/assets/566463/7409414/946d2744-ef26-11e4-9c88-979f67c43fc8.png)

**Comment by miyconst** [comment]
Yes, looks good, but the size is much bigger compare to what we have.

I think, we could not use that big size because of elements number and infinite nesting.
