### ISSUE TITLE
Layout editor: change font-color of tree elements

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#45]
Currently left side tree has `opacity: 0.85;` which makes text difficult to read.

It would be better to apply opacity to background color only. Font color should also be darken a little.

I would change color scheme to match top panel and rid off opacity at all.

**Comment by warpech** [comment]
+1

**Comment by miyconst** [comment]
+1 to which point?

**Comment by warpech** [comment]
I'm sorry, I didn't discover that the last line contradicts the previous one...

I dislike that the color scheme of the layout editor blends too much with Launcher. Maybe the color scheme for the sidebar + toolbar should stand out more? Perhaps make it gray/white as in:

- [After Effects](http://gallery.dpcdn.pl/imgc/Tools/12434/g_-_-x-_-_s_12434x20120507161359_00.png)
- [Unity3D](http://bestwinsoft.com/images/Unity_3D_1.jpg)
- [Audition](http://creativedroplets.com/wp-content/uploads/2013/10/Audition-cc-screenshot.jpg)
- [Cinema 4D](http://www.picturetools.de/!Direkt/DirektUpload/Maxon/R14/screen_broadcast_03.jpg)

**Comment by miyconst** [comment]
Gray and white would be nice and readable, just don't add redundant shadows and opacity.

**Comment by warpech** [comment]
+1 :)

**Comment by miyconst** [comment]
Then I take the issue.

**Comment by miyconst** [comment]
New styles applied.
