### ISSUE TITLE
Layout editor: use static position for sidebar

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#46]
Not sure it is a good idea, but I would like to put sidebar at the left/right side of the content, instead of over content.

This might cause horizontal scroll on small monitors or large websites, but overall it should improve usability.

Buttons to collapse/expand sidebar might be added if needed.

**Comment by warpech** [comment]
I think it makes sense since the scrollbar itself now scrolls to highlighted element: https://github.com/Juicy/juicy-tile-editor/issues/41

**Comment by miyconst** [comment]
Should I remove ability to drag sidebar then?

**Comment by warpech** [comment]
I misunderstood the issue. Once again:

> I would like to put sidebar at the left/right side of the content, instead of over content

For me this would be very challenging, because turning sidebar ON would actually cause the resize and repositioning of the working area. How can I then work on a pixel-perfect layout for my window size?

**Comment by miyconst** [comment]
I am not sure that pixel-perfect layout is required, because the layout should work on all screen sizes. If the screen is too small, then horizontal scroll appears.

Anyway, it is just my suggestion after using layout editor for a while. Now the sidebar is movable and it remembers its position, so not that important as before.

**Comment by warpech** [comment]
@mtornwall uses the layout editor in a small window (800x600), so I guess he would prefer floating tree rather than a tree that pushes the content to the side.

@mtornwall is that right?

If so, then no change needed, I suggest

**Comment by miyconst** [comment]
Okay, I also got used to its current state.
