### ISSUE TITLE
Layout editor: remove shadow overlay

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#47]
I would remove black shadow over entire page. Blue border distinguish selected element good enough.

**Comment by warpech** [comment]
You can experiment with it. `<juicy-highlight>` has `overlay` as a boolean parameter: https://github.com/juicy/juicy-highlight

**Comment by miyconst** [comment]
Which one is better:
![layout-overlay-1](https://cloud.githubusercontent.com/assets/6435556/7374888/7e50c988-eddd-11e4-8bb3-f65955a8a0a7.png)
![layout-overlay-2](https://cloud.githubusercontent.com/assets/6435556/7374889/7e52258a-eddd-11e4-9f75-50ea65377f20.png)

I like the second one.
