### ISSUE TITLE
Layout editor: highlight elements on hover

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#48]
Not very important, but would be nice to highlight html elements when hovered in sidebar.

**Comment by warpech** [comment]
Highlight, but not select? Definitely useful!

**Comment by warpech** [comment]
Approved

**Comment by miyconst** [comment]
Done. Now juicy-highlight has new `fill` attribute: https://github.com/Juicy/juicy-highlight/commit/d0d58f3946c72f3d9a5c60647ce90ac1c1389660.
