### ISSUE TITLE
Remove namespace from imported templates

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#5]
Launcher's namespaced imported templates should not be required to hardcode the namespace inside of the template.

Instead of this:

```html
<template bind="{{SuperCRM}}">
```

We need this:
```html
<template>
```

The model should be accessible for arbitrary code in the imported template, so that a template script can access the data and apply it to any library, be it pure JavaScript/Polymer/React/etc.

**Comment by tomalec** [comment]
Done with https://github.com/Polyjuice/Polyjuice/commit/796cd5872ecb3801624849f0ee2377a56a5e0ce9 and [Juicy/imported-template@0.0.8](https://github.com/Juicy/imported-template/tree/0.0.8)
