### ISSUE TITLE
Layout editor: Save button forgets that it was in dirty state

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#50]
When I turn the layout editor on/off, the Save button forgets that it should be in dirty state.

**Comment by miyconst** [comment]
@tomalec, I have added 

https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/wwwroot/sys/juicy-tile-editor/src/juicy-tile-editor-form.js#L321
```javascript
this.refresh();
```
To `selectedItemsChanged` method, but this behaves very strange. Sometimes it gets into modified state when I select some elements, but don't change them. Sometimes it does not get into modified state when I return back to modified element.

I tried to investigate the issue, but no big success so far.

**Comment by warpech** [comment]
Closing this issue, because it was regarding the discontinued old layout editor.
