### ISSUE TITLE
Layout editor: juicy-tile-list setup should be always preloaded

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/Polyjuice#51]
So we do not have to wait and blink to fetch it asynchronously

**Comment by miyconst** [comment]
@tomalec, is this issue same as https://github.com/Polyjuice/Launcher/issues/123?

**Comment by tomalec** [comment]
Nope, this one is about configuration setup coming in JSON view-model together with partial data

**Comment by tomalec** [comment]
Fix together with new PartialId
