### ISSUE TITLE
Reload the data at (merged) partial without reloading the partial itself

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/Polyjuice#52]
When reloading by re-requesting via `Self.GET` does reload data, but blinks, as it re-attaches HTML in DOM.

`MyPage.Data = newdata` does not notify poly pages.

**Comment by warpech** [comment]
> `MyPage.Data = newdata` does not notify poly pages.

I believe that this is fixed now. If that is not correct, pls make a new issue in the Starcounter issue board.
