### ISSUE TITLE
Layout editor: Prompt before losing layout changes

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#53]
Currently when I make changes in the layout and collapse the editor, it is easy to forget that the changes were not saved. Ideas:

1) Show prompt when closing the editor with unsaved changes
2) Show prompt when navigating away from the page in browser (`window.onunload`)

**Comment by miyconst** [comment]
1) I would rather change color of editor cog. It is often required to close/open editor when applying layout settings for a big page. The prompt might be really annoying.

2) `window.onunload` works fine with page reload and normal links, but hijacked links don't rise the event. The events `window.onpopstate` and `window.onhashchange` also don't occur on hijacked link click.

Should I still implement `window.onunload` prompt?

**Comment by warpech** [comment]
@tomalec WDYT?

**Comment by tomalec** [comment]
@miyconst 's 1. Seems cool if we cold restore dirty state for save buttons when reopening the editor.

2. Personally I do not like such prompts, but at least it is something. What about desired solution with autosaving and keeping pending setup on serverside?

**Comment by miyconst** [comment]
@tomalec, I also dislike such prompts.

About button dirty state I wrote in this issue: https://github.com/Polyjuice/Polyjuice/issues/50

**Comment by miyconst** [comment]
I think the prompt is not necessary, @warpech, @tomalec, close the issue if so, please.

**Comment by warpech** [comment]
I agree a prompt would be annoying after all. Different cog color would be better.
