### ISSUE TITLE
Polyjuice.dll vs Launcher

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#54]
**Every** class and method in [Polyjuice/Polyjuice](https://github.com/Polyjuice/Polyjuice) is heavily tied to [Polyjuice/Launcher](https://github.com/Polyjuice/Launcher), making it impossible to create an alternative Launcher (with different JSON structure, for example without a search bar).

Thus, I vote for moving all the code back to Polyjuice/Launcher. When things get stable and we identify the parts that are really agnostic (perhaps things related to `AddFilterToMiddleware` and `PolyjuiceHtmlMergerPrefix` in [LauncherHelper.cs](https://github.com/Polyjuice/Polyjuice/blob/bb0e5b40a99a301be46762cb3a50e11b63ce4a81/src/LauncherHelper.cs), but not much more), we can move that part back to Polyjuice.

Any votes against this move? @andwah, @tomalec, @alemoi, @Starcounter-Jack?

The reason for my proposal is maintainance. Currently Launcher's view-model is constructed in Polyjuice.dll (which is tied to Starcounter installation version). It should be decoupled for more effective work.

**Comment by warpech** [comment]
@alemoi agreed to do this

**Comment by tomalec** [comment]
Hurray!
