### ISSUE TITLE
Layout editor: clear styles button does not clear background and border styles

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#59]
Steps to reproduce:

1. Start an app.
2. Select a tile.
3. Apply background color or border for the tile.
4. Save changes.
5. Refresh page.
6. Reset all styles by button or apply clean styles from source.
7. The size, priority and groups of tiles will be reset, but the border and background not.

Page reload is required to rid off the background and border, which means that the values are correct in tiles, but not in html elements.

**Comment by warpech** [comment]
Approved

**Comment by miyconst** [comment]
Another issue: Clear button does not work if the layout setup is not yet saved.
Steps to reproduce:

1. Open a page.
2. Clear all styles.
3. Refresh page.
4. Apply source, but not save the styles.
5. Press Clear button, nothing happens.

**Comment by miyconst** [comment]
Another issue: Background color is not restored when applying source. Steps to reproduce:

1. Open a page.
2. Apply background color for a group.
3. Save styles and copy json to somewhere.
4. Refresh page and make sure that the styles are successfully apllied.
5. Clear styles.
6. Apply styles from json again.
7. The group won't have back color, if you click on a group it's property will show the back color though.

This happens only if I clear styles before applying source, if apply source right after page load, then it works as expected.

**Comment by miyconst** [comment]
All of the three issues are fixed.

**Comment by warpech** [comment]
:+1:
