### ISSUE TITLE
Lost icons in the Polyjuice behaves strangely sometimes

### ISSUE THREAD

**Issue by dan31** [Polyjuice/Polyjuice#6]
No special pattern is found. Just clicking around.
![screen shot 2015-02-18 at 11 14 45](https://cloud.githubusercontent.com/assets/7162535/6245707/7fe6b364-b761-11e4-9e40-05f6207ebfd7.png)
This one is activated:
> Enable experimental Web Platform features. Mac, Windows, Linux, Chrome OS, Android
Enable experimental Web Platform features that are in development. #enable-experimental-web-platform-features

**Comment by tomalec** [comment]
Thanks for reporting :)
This is probably `<juicy-tile-list>` issue, as without element queries, and lack of `Element.onResize` event it cannot get exact moment to read, or update it's own with. 
It could also be affected by our routing and imported-template, as tiles-list is rendered with 0 with for the first time.

**Comment by tomalec** [comment]
Fixed by https://github.com/Polyjuice/Launcher/commit/04205d9bd99208ff085ad64c0c459f7cad67f83d
