### ISSUE TITLE
Fractions in layout

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#61]
What is possible right now:

Percentage widths, relative to the parent:

tile 50% width of the parent | tile 50% width of the parent
-------|-------

Pixel widths, absolute:

tile 200px width | tile 200px width
-------|-------

Pixel widths and percentages combined:

tile 200px width | tile 50% width of the parent (not useful at all, because it can only work in a predictable way if the parent width is fixed)
-------|-------

The goal of introducing fractions is to be able to express:

tile 200px width | tile 50% width of the available space | tile 50% width of the available space
-------|-----|---

The sum of the above widths should be 100% width of the parent

Related to:

- Juicy/juicy-tile-grid#6, 
- Polyjuice/Launcher#70 .1 [description at wiki](https://github.com/Polyjuice/Launcher/wiki/Juicy-tiles#widthheight)

**Comment by tomalec** [comment]
I would say that the goal you specified here is to applicable to juicy-tile-list. The term "available space" is the problem. On input (before packing) what would you call "the space"? What packing tries to do is to make no "space left". During packing we need strict sizes: fixed, or at least relative to the container we are packing into.

**Comment by tomalec** [comment]
Therefore I would suggest use of fixed px and percentages in input (JSON), and consider fractions or at least percentages as output (CSS)

**Comment by tomalec** [comment]
So we should not talk about "space left" but rather on behavior when container size changes.

We will be extremely precise when defining setup for backing, and state how tiles shold relate to parent size on runtime(output css for grid)

**Comment by tomalec** [comment]
Short description of responsive design workflow for juicy-tile-grid:
https://github.com/Juicy/juicy-tile-grid/wiki/How-to-create-responsive-design-with-Juicy-elements

And my proposition of "expandable" feature, that uses fixed sizes as input and fractions as output:
https://github.com/Juicy/juicy-tile-grid/wiki/More-on-expandable-size

**Comment by warpech** [comment]
Fractions in juicy-tile-grid are discussed here: https://github.com/Juicy/juicy-tile-grid/issues/8

**Comment by tomalec** [comment]
Implemented, as described in juicy-tile-grid pages
