### ISSUE TITLE
Pattern for combining Save, Cancel buttons

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#62]
As asked by @andwah:

> If several apps expose a [Save] button (let's say on a "Person"). Both buttons may do different stuff on saving. (the end-user will probably "hide" one of the buttons.). Then one apps "Save" button will never be called and maybe important code will never be executed.

One idea that I heard was that maybe there should be some events for `Page` like `OnSave`, `OnCancel`. A Save or Cancel button would execute this handler for current page as well as sibling and child pages.

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Starcounter/issues/2697

**Comment by miyconst** [comment]
I think that:

1. Response for requests with `CallLevel > 1` should never contain a Save/Cancel button.
2. Save button should does nothing but commit transaction.

In this case the end result will never depend on which button was pressed.

If we are going to introduce some page events, then `Saving` and `Validating` would be good. The `Cancelling` event does not have much sense, as it may never occur.

I would like to see `Commiting`, `Commited`, `Restoring`, `Restored` events in transaction though.

**Comment by warpech** [comment]
Re 1: Tempting! @Starcounter-Jack, WDYT? This surely would have radical implications in application UX. I am not sure if the world is ready for that but it is worth considering!

Re 2: We discussed this briefly yesterday with @Starcounter-Jack, and the suggestion was as well that `Save` button should do nothing more then commit a transaction (`Cancel` - roll back a transaction).

As a positive side effect - we would be able to have a "Save all" functionality in Launcher, which would save all transactions always.

It is my apps decision whether cancelling makes sense. Effectively, instead of cancelling a transaction I can also replace the view, so that the previous page with uncommited transaction goes to hell (aka GC).

Problem with validation is that we need to validate all pending transactions before commiting the first one. Or at least this is what I would expect, not to create a half-broken data by using 2 apps that commited OK and 1 app that failed because of invalid input.

**Comment by miyconst** [comment]
Maybe I am completely wrong, but one page should run in scope of only one transaction. When we do `Self.GET` inside a transaction, what would be the transaction for the page created? I guess it would be the same transaction.

So, how could there be multiply long running transactions on the same page?

I agree to don't redirect on `Save`/`Cancel` button click, though I like this behaviour.

Why would we care about other pending transactions when commiting our own? User opens a page to create a new person. Two apps on the page: People & Images. User fills some data and presses `Save` button. Page validation event occurs, both of the apps are subscribed to the event. Images app decides that the image being uploaded is too small and sets `EventArgs.IsValid = false;`. The save function shows errors and stops execution. If no errors, then just commit transaction.

**Comment by warpech** [comment]
Moved to https://github.com/Starcounter/Guidelines/issues/27
