### ISSUE TITLE
Status code: 1011. Reason: Property 'juicyTilesSetup' is readonly.

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#65]
Where this issue came from? I just was trying to save layout setup and get this:

```
WebSocket connection closed. Status code: 1011. Reason: Property 'juicyTilesSetup' is readonly.
```

Not able to reproduce the issue though.

**Comment by chrhol** [comment]
I made some changes in which patches to the server were ignored and which patches returned errors. This is one that previously was ignored, trying to send a patch on a property that is readonly.

Is the JuicyTiles setup modified using patches now? If so the property should be made editable.

**Comment by miyconst** [comment]
Thank you for the explanation, the juicy setup is saved with REST API. 

Looks like something caused a change in the object, but I could not figure out what was that.

Closing the issue for now, will open it again if found how to reproduce it.
