### ISSUE TITLE
Only few sample apps use starcounter-include

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#73]
Only few sample apps use `starcounter-include`. Other apps use `<template is="imported-template">`. I think all samples should be upgraded to `starcounter-include` to avoid confusion.

@tomalec, @miyconst WDYT?

**Comment by tomalec** [comment]
Agree, unless there is a reason. E.g. demo of Starcoutner's flexibility, or conscious disabling SC features.

**Comment by miyconst** [comment]
Also agree. InvoiceDemo could be left with `imported-template`, because it does not require `juicy-tile-editor` and it would be difficult to explain that many Starcounter features in the very first demo.

**Comment by warpech** [comment]
> Also agree. InvoiceDemo could be left with `imported-template`, because it does not require `juicy-tile-editor` and it would be difficult to explain that many Starcounter features in the very first demo.

I don't agree. It is even more difficult to explain why someone needs to change to `starcounter-include` after he was first introduced to `imported-template`.

If we show `starcounter-include` from the beginning (and give a link to a page that summarizes its features), then we will not have problems that someone is using `imported-template` and asking why does his page stopped to show up when he started to use `Self.GET` (I have witnessed this with @malx122)

**Comment by miyconst** [comment]
Okay, then let's replace all of the `imported-template` with `starcounter-include`.

**Comment by warpech** [comment]
This issue is still valid. 

[GitHub search](https://github.com/search?p=4&q=imported-template+sys+filename%3A.html+user%3AStarcounter+user%3AStarcounterSamples+user%3AStarcounterPrefabs+user%3AJuicy+user%3AStarcounter-Jack+user%3APuppetJs+user%3ASmorgasbord-Development&ref=searchresults&type=Code&utf8=%E2%9C%93)

List of files that need to be updated:

- https://github.com/StarcounterPrefabs/Launcher/blob/master/src/Launcher/wwwroot/Launcher/viewmodels/LauncherTemplate.html
- https://github.com/StarcounterSamples/People/blob/master/src/People/wwwroot/People/viewmodels/PersonsPage.html
- https://github.com/StarcounterSamples/People/blob/master/src/People/wwwroot/People/viewmodels/PersonPage.html
- https://github.com/StarcounterSamples/People/blob/master/src/People/wwwroot/People/viewmodels/OrganizationsPage.html
- https://github.com/StarcounterSamples/People/blob/master/src/People/wwwroot/People/viewmodels/OrganizationPage.html
- https://github.com/StarcounterSamples/Website/blob/master/src/Website/wwwroot/Website/viewmodels/StandalonePage.html
- https://github.com/StarcounterSamples/Website/blob/master/src/Website/wwwroot/Website/viewmodels/LayoutPage.html
- https://github.com/StarcounterSamples/Barcodes/blob/master/src/Barcodes/wwwroot/Barcodes/viewmodels/StandalonePage.html
- https://github.com/StarcounterSamples/Chatter/blob/master/wwwroot/Chatter/ViewModels/StandalonePage.html
- https://github.com/StarcounterSamples/Products/blob/master/src/Products/wwwroot/Products/viewmodels/StandalonePage.html
- https://github.com/StarcounterSamples/Skyper/blob/master/src/Skyper/wwwroot/Skyper/viewmodels/StandalonePage.html
- https://github.com/StarcounterSamples/Content/blob/master/src/Content/wwwroot/Content/viewmodels/StandalonePage.html
- https://github.com/StarcounterSamples/Images/blob/master/src/Images/wwwroot/Images/viewmodels/StandalonePage.html
- https://github.com/StarcounterSamples/Procurement/blob/master/src/Procurement/wwwroot/Procurement/viewmodels/StandalonePage.html
- https://github.com/StarcounterSamples/UserAdmin/blob/master/src/UserAdmin/wwwroot/UserAdmin/viewmodels/launcher/StandalonePage.html
- https://github.com/StarcounterSamples/AppStoreClient/blob/master/src/AppStoreClient/wwwroot/AppStoreClient/viewmodels/StandalonePage.html
- https://github.com/StarcounterSamples/Cartographer/blob/master/src/Cartographer/wwwroot/Cartographer/viewmodels/LocationsPage.html
- https://github.com/Starcounter/InvoiceDemo/blob/master/src/InvoiceDemo1/wwwroot/InvoiceDemo/InvoicePage.html
-https://github.com/Starcounter/InvoiceDemo/blob/master/src/InvoiceDemo2/wwwroot/InvoiceDemo/MasterPage.html
- https://github.com/Starcounter/InvoiceDemo/blob/master/src/InvoiceDemo3/wwwroot/InvoiceDemo/InvoicePage.html
- https://github.com/Starcounter/InvoiceDemo/blob/master/src/InvoiceDemo3/wwwroot/InvoiceDemo/InvoicesPage.html
- https://github.com/Starcounter/InvoiceDemo/blob/master/src/InvoiceDemo3/wwwroot/InvoiceDemo/LauncherWrapperPage.html
- https://github.com/Starcounter/InvoiceDemo/blob/master/src/InvoiceDemo3/wwwroot/InvoiceDemo/MasterPage.html
- https://github.com/Starcounter/RemoteAccess/blob/master/src/RemoteAccess/wwwroot/remoteaccessserver/StandalonePage.html
- https://github.com/Starcounter/VersionManager/blob/master/src/wwwroot/VersionManager/viewmodels/StandalonePage.html
- https://github.com/Smorgasbord-Development/Calendar/blob/b54f7b69458be487e06f685061b8fda3bc4a2186/src/Calendar/wwwroot/Calendar/viewmodels/launcher/StandalonePage.html

**Comment by warpech** [comment]
Right now all apps that are not in StarcounterAppsFreezer make proper use of `starcounter-include`. Closing as done
