### ISSUE TITLE
Add ~ operator to Stracounter dependency in package.config of the sample apps

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#75]
Currently, most of sample apps appear outdated in Administrator:

![screenshot 2015-11-10 19 21 27](https://cloud.githubusercontent.com/assets/566463/11071275/419392da-87e0-11e5-80da-ce5ee6400554.png)

I propose to update all the sample apps to use current stable `~2.1.177` (if they work with current stable).

It was already done in UserAdmin: https://github.com/StarcounterSamples/UserAdmin/blob/master/src/UserAdmin/package/package.config#L14

**Comment by warpech** [comment]
As @andwah pointed out to me today, ~ is a convention used by NPM and Bower, but this is not a convention in Microsoft world (see https://github.com/aspnet/dnx/issues/1014). There was some initial work on it but seems to be dropped: https://github.com/aspnet/dnx/pull/1057

In NuGet the Maven syntax is used. More specifically:

- [`packages.config`](https://docs.nuget.org/create/versioning) uses `2.1.177` where it means 2.1.177 or higher
- [`project.json`](http://docs.nuget.org/Consume/ProjectJson-Intro) allows to use `2.1.177-*` or `2.1.*`. The latter is [compatible](https://github.com/npm/node-semver) with NPM and Bower

So @andwah, shall we change all `~2.1.177` to `2.1.*`? This would make us compatible with both NPM and Nuget3.

**Comment by andwah** [comment]
I think the Maven syntax is easier to understand.

**Comment by warpech** [comment]
I think that Maven syntax is easily confusing, because in Maven syntax, `2.1.177` means that your app is compatible with any future Starcounter version. I think we wanted to avoid that? Since we know that Starcounter 2.2.0 will be a breaking change (otherwise we would not bump the number), the app should be tested and rereleased with that version.

**Comment by warpech** [comment]
Closing as no longer relevant. Otherwise, pls start a new discussion in Warehouse repo
